apiVersion: gobackup.io/v1
kind: S3
metadata:
  name: test-s3
  namespace: manual-test
spec:
  bucket: "test-bucket"
  region: "us-east-1"
  accessKeyID: "test-key"
  secretAccessKey: "test-secret"
  maxRetries: 3
  storageClass: ""
  forcePathStyle: false
  endpoint: "" # Custom endpoint