apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gobackup-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "gobackup-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gobackup-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "gobackup-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

