{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gobackup-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gobackup-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "gobackup-operator.selectorLabels" . | nindent 4 }}
{{- end }}

