{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gobackup-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gobackup-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gobackup-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "gobackup-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

