apiVersion: gobackup.io/v1
kind: PostgreSQL
metadata:
  name: example-postgresql
  namespace: gobackup-operator-test
spec:
  host: "host.docker.internal"
  port: 5432
  username: "postgres"
  password: "mysecretpassword"
  database: "my_database"